[api]
port = 54321

[db]
port = 54322

[studio]
port = 54323

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.apple]
enabled = false

[auth.sms.twilio]
enabled = false
account_sid = ""
message_service_sid = ""
auth_token = ""

[storage]
file_size_limit = "5MB"
